require("impatient")
require("plugins")
require("config.vim_let")
-- require("config.neo_conf")
-- require("config.lspkind")
-- require("config.cmp")
-- require("config.mason_lsp")
-- require("config.navic")
-- require("config.autopair")
-- require("config.lspsaga")
-- require("config.comment_nvim")
-- require("config.mason_nvim_dap")
-- require("config.treesitter")
-- require("config.telescope")
-- require("config.barbecue_config")
-- require('config.symbols-outline')
-- require("config.indentline")
-- require("config.git")
-- require("config.toggleterm")
-- require("config.trouble")
-- require("config.neoclip")
-- require("config.hlargs")
-- require("config.surround")
-- require("config.dashboard")
-- require("config.colorize")
-- require("config.nvim-toggler")
-- require("config.runsnip")
-- require("config.ufo")
-- require("config.hlslens")
-- require("config.statuscol")
-- require("config.neo_dev")
-- require("config.coloursheme")

